### PR TITLE
localhost (port 80) allowed for CORS usage

### PR DESCRIPTION
**Pull request by CandleHater**
Would like to allow localhost without a custom port in cors.

### CODE REVIEW

**Comment by nolim1t** [comment]
LGTM

**Comment by mayankchhabra** [comment]
Thanks for the PR, @CandleHater! I'm curious what's your use-case it? Do you want to run the dashboard specifically on port 80?

**Comment by CandleHater** [comment]
I spinned up an umbrel stack and straight up opened locahost. After writing down the seed and setting up nearly everything, it was a little dissapointing that this error popped up at that point and not prior. I just want to prevent me and others from getting to this point.

**Comment by mayankchhabra** [comment]
Fair enough. 

Have you tried setting the `DEVICE_HOST` variable to `http://localhost` in `docker-compose.yml` (for both manager and middleware)? 

https://github.com/getumbrel/umbrel/blob/b47d1cb16d9e62bd8c48977db13870a65b6f38af/docker-compose.yml#L101
https://github.com/getumbrel/umbrel/blob/b47d1cb16d9e62bd8c48977db13870a65b6f38af/docker-compose.yml#L127

**Comment by CandleHater** [comment]
No, but saw that also afterwards. Just thought it might be nice to either prevent opening with a non CORS accepted URLs or just allow that one, so others not checking things prior (like me here) anyway can just get started without interruption. Not really important though.

**Comment by mayankchhabra** [comment]
Great, thanks for bringing this up and fixing it. 🙏

As one of the super early users giving Umbrel a shot, feel free to raise more issues, and share feedback directly with us on our [community chat](https://t.me/getumbrel).

**Pull request merged**
